### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jondmca** [learn-co-curriculum/phase-0-organizing-work-on-your-computer#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4327/pages/organizing-your-work-for-this-course?module_item_id=251518

## What should be changed?

In the first sentence the "you" should be "your"

**Comment by graciemcguire** [comment]
Thanks for flagging @jondmca !
